#!/usr/bin/env bash
# Mirror the pinned CI tools (see tools.lock) into the `ci-tools` GitHub release.
# Run by .github/workflows/seed-ci-tools.yml, or locally to bootstrap the release:
#   GH_TOKEN=$(gh auth token) bash scaffolding/ci/seed.sh
#
# Portable across Linux and macOS (uses `shasum`, not `sha256sum`).
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
lock="$here/tools.lock"
tag=$(jq -r .release_tag "$lock")
work=$(mktemp -d)
sums="$work/SHA256SUMS"
: > "$sums"

for tool in $(jq -r '.tools | to_entries[] | select(.value.platforms != null) | .key' "$lock"); do
  for plat in linux-x86_64 macos-aarch64; do
    url=$(jq -r --arg t "$tool" --arg p "$plat" '.tools[$t].platforms[$p].url' "$lock")
    asset=$(jq -r --arg t "$tool" --arg p "$plat" '.tools[$t].platforms[$p].asset' "$lock")
    exp=$(jq -r --arg t "$tool" --arg p "$plat" '.tools[$t].platforms[$p].sha256 // ""' "$lock")
    shaurl=$(jq -r --arg t "$tool" --arg p "$plat" '.tools[$t].platforms[$p].sha256_url // ""' "$lock")

    echo ">> $tool $plat"
    curl -fsSL "$url" -o "$work/$asset"
    actual=$(shasum -a 256 "$work/$asset" | awk '{print $1}')
    if [ -n "$shaurl" ]; then exp=$(curl -fsSL "$shaurl" | awk '{print $1}'); fi
    if [ -n "$exp" ]; then
      [ "$exp" = "$actual" ] || { echo "provenance mismatch for $asset: $exp != $actual" >&2; exit 1; }
      echo "   provenance OK"
    else
      echo "   TOFU, recorded: $actual"
    fi
    echo "$actual  $asset" >> "$sums"
  done
done

echo "----- SHA256SUMS -----"; cat "$sums"

if gh release view "$tag" >/dev/null 2>&1; then
  gh release delete "$tag" --yes --cleanup-tag
fi
gh release create "$tag" \
  --title "CI tool mirror" \
  --notes "Pinned CI tools, generated by scaffolding/ci/seed.sh. Do not edit by hand." \
  --latest=false \
  "$work"/*

echo "Done: release '$tag' updated."
